### PR TITLE
Product additions #70

### PR DESCRIPTION
**Pull request by z-priest**
This PR is to address some of what is requested in https://github.com/CERTCC/VINCE/issues/70.

The first commit is a majority of this PR which includes: adding product storage to contacts; recalling those contacts within edit vulnerability; some table additions and UI changes to above respective actions.

The second commit is a fix to remove some auto-filled data using a fixtures file.

### CODE REVIEW

**Comment by z-priest** [comment]
Working on cleaning up the vince/migrations section asap to include as part of this PR.

**Comment by sei-vsarvepalli** [comment]
A number of issues with this PR. Hopefully we can chat @z-priest in the next meeting. Did not pass any of the manual tests - I added the relevant notes inline for the code. I have also added notes about the app development to move more to Browser-form validation - a client-side validation pattern to avoid content submit without local validation.

Thanks
Vijay

**Comment by sei-vsarvepalli** [comment]
Enclosed are the screenshots as promised. There is a new Vendor called "Steele" that was added with a product tree of "Larry version 1.9 <= 1.0" and "Junior"

You can see the Form errors, and the Select auto does not work. There seems to be no asynchronous Javascript that collect the Vendor-Product tuple tree from the database. The command-line and the Firefox `Automate Click` plugin screenshots are also enclosed. The product-0-organization is the one that is not populated and left blank before submit. 

Screen Shot 2023-01-31 at 4 11 05 PM
Screen Shot 2023-01-31 at 4 10 11 PM
Screen Shot 20
<img width=
23-01-31 at 4 09 48 PM" src="https://user-images.githubusercontent.com/19911912/215884776-97a4f912-8c75-4d79-9334-38526f68d69d.png">

**Comment by z-priest** [comment]
@sei-vsarvepalli 

Problems that exist with this PR:
1. Missing django-multiselectfield from requirements.txt
2. Missing multiselectfield 'INSTALLED_APPS' in settings.py
3. Development branch is a few commits behind main (compare UI pictures).

One of the above issues might have resulted in the issue with product-0-organization not being pulled in.

Solution being worked on:
1. PR to get development branch on main.
2. Fix what needs fixing (ensure migrations fixed by requirements.txt, squash migrations, org-dropdown auto poulate, async)
3. New PR.
4. Request another test.

We can close this PR and I will submit these in order.

One of the above cases likely affected the results.
Screenshot1
Screenshot2
Screenshot3

**Pull request closed without merging**
